export const SYNC_IMAGES = 'image/SYNC_IMAGES';
export const SELECT_IMAGE = 'image/SELECT_IMAGE';
export const DOWNLOAD_ORIGINAL_IMAGE = 'image/DOWNLOAD_ORIGINAL_IMAGE';
export const SET_SELECTED_CATEGORY = '/image/SET_SELECTED_CATEGORY';
